### ISSUE TITLE
The one three-em dash should be replaced by single em dash

### ISSUE THREAD

**Issue by bobrk** [bobrk/edna-ferber_so-big#2]

**Comment by bobrk** [comment]
I think this is an elided swear word, thus should have the 3-em dash, but it might be an interpretation.

**Comment by bobrk** [comment]
8.7.7.8.5

**Comment by maticstric** [comment]
Yea I thought so too initially, but from the context it seems more likely that he stopped himself from saying a curse word once he realized that "his rival was a woman" and then changed his tone to "You can’t go in there, missus". But I agree it's up to interpretation. I'd make it an em dash but if you want to ask on the google group and see how other people feel that be good too.

**Comment by bobrk** [comment]
I agree, thanks for your input! I'll just go with the em-dash.
