### ISSUE TITLE
All the two-em dashes, besides the one in chapter 15, should be replaced by single em dashes.

### ISSUE THREAD

**Issue by bobrk** [bobrk/edna-ferber_so-big#3]
The two-em dash in chapter 3 is a partial word, so leaving it as is.

**Comment by maticstric** [comment]
I think it's more of an interruption of "thoughts", which seems like it should be a single em dash. If it were just an obscured word there would probably be a period after the dash.

Also, I realized that the "b" should probably be within the italics as well since it's part of a non-English word.

**Comment by bobrk** [comment]
Agree.
